#include <iostream>

#include "src/algorithms/string.h"

int main()
{
    ds::algorithms::string::find_most_common_symbol::twoCyclesMethod("ababahghjgjhghjkghjgjkghjfghftyftyfjkahfjksahfkjahsjkfasjkfhasjkfhjkashfjkashfjkaskjfhasfhkashfjkasghfghfreterereerrererererfchgcncbncjjahsfjkashfkjashfkjasfhjkashfkjashfkjaskjashfkjashfjksahfjkashfhasjkfhasjkfjkashfjkasfhkjaghfkfghfhjftyvhghghghvghjdfdtrdtrdrhdhfdfgdfgdhgdfgdhdgffytfuyf");
    ds::algorithms::string::find_most_common_symbol::unorderedSetMethod("ababahghjgjhghjkghjgjkghjfghftyftyfjkahfjksahfkjahsjkfasjkfhasjkfhjkashfjkashfjkaskjfhasfhkashfjkasghfghfreterereerrererererfchgcncbncjjahsfjkashfkjashfkjasfhjkashfkjashfkjaskjashfkjashfjksahfjkashfhasjkfhasjkfjkashfjkasfhkjaghfkfghfhjftyvhghghghvghjdfdtrdtrdrhdhfdfgdfgdhgdfgdhdgffytfuyf");
    ds::algorithms::string::find_most_common_symbol::unorderedMapMethod("ababahghjgjhghjkghjgjkghjfghftyftyfjkahfjksahfkjahsjkfasjkfhasjkfhjkashfjkashfjkaskjfhasfhkashfjkasghfghfreterereerrererererfchgcncbncjjahsfjkashfkjashfkjasfhjkashfkjashfkjaskjashfkjashfjksahfjkashfhasjkfhasjkfjkashfjkasfhkjaghfkfghfhjftyvhghghghvghjdfdtrdtrdrhdhfdfgdfgdhgdfgdhdgffytfuyf");

    return 0;
}